#!/bin/bash
eval "$(conda shell.bash hook)"
conda activate lora_182
# source /home/JJteam/.load_cu102
# source /home/JJteam/.load_cu113
# conda activate lora
​
# export LARGE_KERNEL_CONV_IMPL='/home/shiweil/Projects/cutlass/examples/19_large_depthwise_conv2d_torch_extension'
export LARGE_KERNEL_CONV_IMPL='/data/cutlass/examples/19_large_depthwise_conv2d_torch_extension'
#module purge
#module load 2021
#module load CUDA/11.3.1
#module load PyTorch/1.10.0-foss-2021a-CUDA-11.3.1


bash tools/dist_train.sh  configs/convnext/upernet_convnext_tiny_512_80k_ade20k_ss_decomp_51.py 8  \
  --work-dir Results/ADE20_decomp_51/ --seed 0 --deterministic    \
   --options model.pretrained=LoRA_ERK_s1.5/120epochs/checkpoint-best.pth

source deactivate
